wipefs -a /dev/sdb
wipefs -a /dev/sdc
wipefs -a /dev/sdd
wipefs -a /dev/sde
wipefs -a /dev/sdg
wipefs -a /dev/sdh
wipefs -a /dev/sdi
wipefs -a /dev/sdj
wipefs -a /dev/sdk
wipefs -a /dev/sdl
sgdisk --zap-all /dev/sdb
sgdisk --zap-all /dev/sdc
sgdisk --zap-all /dev/sdd
sgdisk --zap-all /dev/sde
sgdisk --zap-all /dev/sdg
sgdisk --zap-all /dev/sdh
sgdisk --zap-all /dev/sdi
sgdisk --zap-all /dev/sdj
sgdisk --zap-all /dev/sdk
sgdisk --zap-all /dev/sdl
